#ifndef KEYTAB_H
#define KEYTAB_H


#define CTRL 0x01  //
#define SHIFT 0x02 //
#define ALT 0x04   //
#define GUI 0x08   //
#define KEYA 4 			//
#define KEYB 5 			//
#define KEYC 6 			//
#define KEYD 7 			//
#define KEYE 8 			// 
#define KEYF 9 			//
#define KEYG 10 			//
#define KEYH 11 			//
#define KEYI 12 			//
#define KEYJ 13			//
#define KEYK 14			//
#define KEYL 15			//
#define KEYM 16			//
#define KEYN 17			//
#define KEYO 18			//
#define KEYP 19			//
#define KEYQ 20			//
#define KEYR 21			//
#define KEYS 22			//
#define KEYT 23			//
#define	KEYU 24			//
#define KEYV 25			//
#define KEYW 26			//
#define KEYX 27			//
#define KEYY 28			//
#define KEYZ 29			//
#define KEY1 30			//
#define KEY2 31			//
#define KEY3 32			//
#define KEY4 33			//
#define KEY5 34			//
#define KEY6 35			//
#define KEY7 36			//
#define KEY8 37			//
#define KEY9 38			//
#define KEY0 39			//
#define KEYENTER 40 		//
#define KEYESCAPE 41 		//
#define KEYBACKSPACE 42 	// 
#define KEYTAB 43 			//
#define KEYSPACE 44 		//
#define KEYSUBTRACT 45 	// 
#define KEYEQUAL 46		//
#define KEYLBRACKET 47 	//
#define KEYRBRACKET 48		//
#define KEYBSLASH 49		//
#define KEYSEMICOLON 51 	//
#define KEYQUOTE 52		//
#define KEYGRAVE 53		//
#define KEYCOMMA 54		//
#define KEYPERIOD 55		//
#define KEYFSLASH 56		//
#define KEYCAPSLOCK 57		//
#define KEYF1 58			//
#define KEYF2 59			//
#define KEYF3 60			//
#define KEYF4 61			//
#define KEYF5 62			//
#define KEYF6 63			//
#define KEYF7 64			//
#define KEYF8 65			//
#define KEYF9 66			//
#define KEYF10 67			//
#define KEYF11 68			//
#define KEYF12 69			//
#define KEYPRINTSCREEN 70	//
#define KEYSCROLLLOCK 71	//
#define KEYPAUSE 72		//
#define KEYINSERT 73		//
#define KEYHOME 74			//
#define KEYPAGEUP 75		//
#define KEYDEL 76			//
#define KEYEND 77			//
#define KEYPAGEDOWN 78		//
#define KEYRIGHT 79		//
#define KEYLEFT 80			//
#define KEYDOWN 81			//
#define KEYUP 82			//
#define KEYNUMLOCK 83		//
#define KEYKPDIV 84		//
#define KEYKPMULTI 85		//
#define KEYKPSUB 86		//
#define KEYKPADD 87		//
#define KEYKPENTER 88		//
#define KEYKP1 89			//
#define KEYKP2 90			//
#define KEYKP3 91			//
#define KEYKP4 92			//
#define KEYKP5 93			//
#define KEYKP6 94			//	
#define KEYKP7 95			//
#define KEYKP8 96			//
#define KEYKP9 97			//
#define KEYKP0 98			//
#define KEYKPPOINT 99		//
#define KEYAPP 102 		//
#define KEYKPEQUAL 103		//
#define KEYLCTRL 224		//
#define KEYLSHIFT 225		//
#define KEYLALT 226		//
#define KEYLGUI 227		//
#define KEYRCTRL 228		//
#define KEYRSHIFT 229		//
#define KEYRALT 230		//
#define KEYRGUI 231		//

#endif //
